version: 2
jobs:
  asan:
    docker:
      - image: rnburn/clang
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/setup_bazel.sh
      - run: ./ci/do_ci.sh bazel.asan

  tsan:
    docker:
      - image: rnburn/clang
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/setup_bazel.sh
      - run: ./ci/do_ci.sh bazel.tsan

  cmake:
    docker:
      - image: rnburn/clang
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/do_ci.sh cmake

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - asan
      - tsan
      - cmake
